package com.draagon.meta.generator.direct;

import com.draagon.meta.field.MetaField;
import com.draagon.meta.object.MetaObject;
import com.draagon.meta.loader.MetaDataLoader;

/**
 * Object-specific generation context for MetaObject code generation
 * Contains state and utilities specific to object/field generation patterns
 */
public class GenerationContext extends BaseGenerationContext<MetaObject> {
    
    // Object-specific state
    private MetaField currentField;
    
    public GenerationContext(MetaDataLoader loader) {
        super(loader);
    }
    
    // Object-specific state management
    public GenerationContext setCurrentObject(MetaObject object) {
        setCurrentItem(object);
        return this;
    }
    
    public MetaObject getCurrentObject() { 
        return getCurrentItem(); 
    }
    
    public GenerationContext setCurrentField(MetaField field) {
        this.currentField = field;
        return this;
    }
    
    public MetaField getCurrentField() { 
        return currentField; 
    }
    
    @Override
    public String getContextType() {
        return "object";
    }
    
    @Override
    public String resolveVariables(String template) {
        if (template == null) return null;
        
        String result = template;
        
        // Object-specific variable substitution
        MetaObject currentObject = getCurrentObject();
        if (currentObject != null) {
            result = result.replace("${object.name}", currentObject.getName())
                          .replace("${object.shortName}", currentObject.getShortName())
                          .replace("${object.package}", currentObject.getPackage());
        }
        
        // Field-specific variable substitution
        if (currentField != null) {
            result = result.replace("${field.name}", currentField.getName())
                          .replace("${field.type}", currentField.getDataType().toString());
        }
        
        // Common substitutions
        if (currentPackage != null) {
            result = result.replace("${package}", currentPackage);
        }
        
        if (currentClassName != null) {
            result = result.replace("${className}", currentClassName);
        }
        
        return result;
    }
    
    @Override
    protected void initializeDefaultFragments() {
        // Add default Java code fragments for object/field generation
        addCodeFragment("java.getter.javadoc", new CodeFragment(
            "/**\n" +
            " * Gets the ${field.name} value\n" +
            " * @return ${field.javaType} the ${field.name}\n" +
            " */"
        ));
        
        addCodeFragment("java.setter.javadoc", new CodeFragment(
            "/**\n" +
            " * Sets the ${field.name} value\n" +
            " * @param ${field.name} the ${field.name} to set\n" +
            " */"
        ));
        
        addCodeFragment("java.getter.signature", new CodeFragment(
            "public ${field.javaType} get${field.nameCapitalized}()"
        ));
        
        addCodeFragment("java.setter.signature", new CodeFragment(
            "public void set${field.nameCapitalized}(${field.javaType} ${field.name})"
        ));
        
        addCodeFragment("java.interface.getter", new CodeFragment(
            "public ${field.javaType} get${field.nameCapitalized}();"
        ));
        
        addCodeFragment("java.interface.setter", new CodeFragment(
            "public void set${field.nameCapitalized}(${field.javaType} ${field.name});"
        ));
        
        addCodeFragment("java.class.header", new CodeFragment(
            "/**\n" +
            " * Generated class for ${object.name}\n" +
            " * @generated by MetaObjects Direct Generator\n" +
            " */\n" +
            "public ${classType} ${className}${superClass} {"
        ));
    }
    
    // Convenience methods for fluent interface
    @Override
    public GenerationContext setProperty(String key, Object value) {
        super.setProperty(key, value);
        return this;
    }
    
    @Override 
    public GenerationContext addCodeFragment(String name, CodeFragment fragment) {
        super.addCodeFragment(name, fragment);
        return this;
    }
    
    @Override
    public GenerationContext addPlugin(BaseGenerationPlugin<MetaObject> plugin) {
        super.addPlugin(plugin);
        return this;
    }
    
    @Override
    public GenerationContext setCurrentPackage(String packageName) {
        super.setCurrentPackage(packageName);
        return this;
    }
    
    @Override
    public GenerationContext setCurrentClassName(String className) {
        super.setCurrentClassName(className);
        return this;
    }
    
    @Override
    public GenerationContext addImport(String importName) {
        super.addImport(importName);
        return this;
    }
    
    @Override
    public GenerationContext putCache(String key, Object value) {
        super.putCache(key, value);
        return this;
    }
}