package ${package};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

/**
 * Main Spring Boot application class for ${artifactId}.
 *
 * This MetaObjects application demonstrates:
 * - Metadata-driven domain modeling with JSON definitions
 * - Automatic code generation using Mustache templates
 * - Standard JPA persistence with Spring Data repositories
 * - Modern Identity and Relationship patterns
 * - Complete REST API with generated domain objects
 *
 * Generated by MetaObjects Application Archetype v6.2.6
 */
@SpringBootApplication
@EnableJpaRepositories
@EnableTransactionManagement
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}